name: "✅ タスク"
description: "小さめの作業・リファクタ・雑務"
title: "[Task] "
labels: ["chore"]
body:
  - type: textarea
    id: what
    attributes:
      label: やること
      placeholder: "- [ ] 例: WhenGreenFlagClicked の並行実行を実装"
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: 補足
      required: false
